overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(PG_
    - \(OSD_
    - \(OBJECT_
    - \(POOL_APP_NOT_ENABLED\)
    - \(MON_DOWN\)
    - mons down
    - application not enabled on pool
    - do not have an application enabled
    - pool application
    - out of quorum
    - needs hit_set_type to be set but it is not
tasks:
- workunit:
    clients:
      client.0:
        - rados/test_python.sh
