{
 "title": "Ceph - Filesystem Overview",
 "description": "Ceph CephFS overview for official Ceph Prometheus plugin.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "name",
    "label": "Filesystem",
    "query": {
     "query": "label_values(ceph_fs_metadata{cluster=~\"$cluster|\", }, name)"
    }
   },
   {
    "name": "mdatapool",
    "label": "metadata pool",
    "query": {
     "query": "label_values(ceph_fs_metadata{cluster=~\"$cluster|\",  name=~\"$name\"}, metadata_pool)"
    }
   },
   {
    "name": "datapool",
    "label": "data pool",
    "query": {
     "query": "label_values(ceph_fs_metadata{cluster=~\"$cluster|\",  name=~\"$name\"}, data_pools)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filesystems",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_fs_metadata{cluster=~\"$cluster|\", name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Metadata used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})"
    }
   ]
  },
  {
   "title": "Metadata bandwidth read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})"
    }
   ]
  },
  {
   "title": "Data bandwidth read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Client requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_server_handle_client_request{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "Client sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_sessions_session_count{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "MDS inodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_inodes{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "Metadata bandwidth write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data bandwidth write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Metadata used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}) / (sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}) + sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})))) * 100",
     "legendFormat": "Metadata Used"
    }
   ]
  },
  {
   "title": "Metadata IOPS read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}) / (sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}) + sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})))) * 100",
     "legendFormat": "Data Used"
    }
   ]
  },
  {
   "title": "Data IOPS read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Forward requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_forward{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "Reply latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ceph_mds_reply_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})) / sum(increase(ceph_mds_reply_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "MDS caps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_caps{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "Metadata IOPS write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data IOPS write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "MDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_server_handle_client_request{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Forward requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_forward{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Slave requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_server_handle_slave_request{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Session count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_sessions_session_count{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Reply latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (increase(ceph_mds_reply_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})) / sum by (ceph_daemon) (increase(ceph_mds_reply_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_objecter_op_r{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(ceph_objecter_op_w{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"}))",
     "legendFormat": "Write Ops"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Log submit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_log_evadd{cluster=~\"$cluster|\", }[$__rate_interval]) * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Log events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_log_ev{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Log segments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_log_seg{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    { "title": "Active alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 } }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_mem_ino{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Exported inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_exported_inodes{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Imported inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_imported_inodes{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Dentries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_mem_dn{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Caps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_caps{cluster=~\"$cluster|\", } * on(ceph_daemon) group_left() (ceph_mds_metadata{cluster=~\"$cluster\"} * on(fs_id) group_left(name) ceph_fs_metadata{cluster=~\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool storage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"}) + sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(ceph_pool_raw_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"})",
       "legendFormat": "Raw Used"
      }
     ]
    },
    {
     "title": "Objects in pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ceph_pool_objects{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})",
       "legendFormat": "Objects"
      },
      {
       "expr": "sum(ceph_pool_dirty{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})",
       "legendFormat": "Dirty Objects"
      },
      {
       "expr": "sum(ceph_pool_quota_objects{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})",
       "legendFormat": "Quota Objects"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}) / sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"} + ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"})"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\",  pool_id=~\"$mdatapool\"}[$__rate_interval]))",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool storage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"^$datapool$\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$datapool$\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$datapool$\"}) + sum(ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"^$mdatapool$\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(ceph_pool_raw_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"^$datapool$\"})",
       "legendFormat": "Raw Used"
      }
     ]
    },
    {
     "title": "Objects in pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ceph_pool_objects{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})",
       "legendFormat": "Objects"
      },
      {
       "expr": "sum(ceph_pool_dirty{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})",
       "legendFormat": "Dirty Objects"
      },
      {
       "expr": "sum(ceph_pool_quota_objects{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})",
       "legendFormat": "Quota Objects"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}) / sum(ceph_pool_bytes_used{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"} + ceph_pool_max_avail{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"})"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\",  pool_id=~\"$datapool\"}[$__rate_interval]))",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  }
 ]
}