overrides:
  ceph:
    log-ignorelist:
      - inode wrongly marked free
      - bad backtrace on inode
      - inode table repaired for inode
      - Scrub error on inode
      - Scrub error on dir
      - Metadata damage detected
tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_forward_scrub
