---
name: "Pull Request Triage"
on: pull_request_target
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels based on modified files
        uses: actions/labeler@9794b1493b6f1fa7b006c5f8635a19c76c98be95
        with:
          sync-labels: ''
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Assign to Dashboard project
        uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
        if: contains(github.event.pull_request.labels.*.name, 'dashboard')
        with:
          project: https://github.com/ceph/ceph/projects/6          
      - name: Assign milestone based on target brach name
        uses: iyu/actions-milestone@dbf7e5348844c9ddc6b803a5721b85fa70fe3bb9
        with:
          configuration-path: .github/milestone.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
