overrides:
  ceph:
    conf:
      mgr:
        debug mgr: 20
        debug ms: 1
        debug finisher: 20
        debug client: 20
    log-whitelist:
      - OSD full dropping all updates
      - OSD near full
      - pausewr flag
      - failsafe engaged, dropping updates
      - failsafe disengaged, no longer dropping
      - is full \(reached quota
      - POOL_FULL
      - POOL_BACKFILLFULL

tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_volumes
