tasks:
- install:
- ceph:
- tox: [ client.0 ]
- keystone:
    client.0:
      force-branch: stable/xena
      services:
        - name: swift
          type: object-store
          description: Swift Service
- rgw:
    client.0:
      frontend_prefix: /swift
      use-keystone-role: client.0
- tempest:
    client.0:
      sha1: 30.0.0
      force-branch: master
      use-keystone-role: client.0
      auth:
        admin_username: admin
        admin_project_name: admin
        admin_password: ADMIN
        admin_domain_name: Default
        tempest_roles: admin
      identity:
        uri: http://{keystone_public_host}:{keystone_public_port}/v2.0/
        uri_v3: http://{keystone_public_host}:{keystone_public_port}/v3/
        auth_version: v3
        admin_role: admin
        default_domain_name: Default
      object-storage:
        reseller_admin_role: admin
      object-storage-feature-enabled:
        container_sync: false
        discoverability: true
      blocklist:
        - .*test_account_quotas_negative.AccountQuotasNegativeTest.test_user_modify_quota
        - .*test_container_acl_negative.ObjectACLsNegativeTest.*
        - .*test_container_services_negative.ContainerNegativeTest.test_create_container_metadata_.*
        - .*test_container_staticweb.StaticWebTest.test_web_index
        - .*test_container_staticweb.StaticWebTest.test_web_listing_css
        - .*test_container_synchronization.*
        - .*test_object_services.PublicObjectTest.test_access_public_container_object_without_using_creds
        - .*test_object_services.ObjectTest.test_create_object_with_transfer_encoding
        - .*test_container_services.ContainerTest.test_create_container_with_remove_metadata_key
        - .*test_container_services.ContainerTest.test_create_container_with_remove_metadata_value
        - .*test_object_expiry.ObjectExpiryTest.test_get_object_after_expiry_time
        - .*test_object_expiry.ObjectExpiryTest.test_get_object_at_expiry_time

overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw keystone api version: 3
        rgw keystone accepted roles: admin,Member
        rgw keystone implicit tenants: true
        rgw keystone accepted admin roles: admin
        rgw swift enforce content length: true
        rgw swift account in url: true
        rgw swift versioning enabled: true
        rgw keystone admin domain: Default
        rgw keystone admin user: admin
        rgw keystone admin password: ADMIN
        rgw keystone admin project: admin
