overrides:
  ceph:
    conf:
      osd:
        osd mclock profile: high_recovery_ops
tasks:
  - install:
  - ceph:
      config:
        global:
          osd pool default size : 3
          osd pool default min size : 2
      # tests may leave mgrs broken, so don't try and call into them
      # to invoke e.g. pg dump during teardown.
      wait-for-scrub: false
      log-ignorelist:
        - overall HEALTH_
        - \(MGR_DOWN\)
        - \(MDS_ALL_DOWN\)
        - \(MDS_UP_LESS_THAN_MAX\)
        - \(FS_WITH_FAILED_MDS\)
        - \(FS_DEGRADED\)
        - \(PG_
        - \(OSDMAP_FLAGS\)
        - replacing it with standby
        - No standby daemons available
        - \(POOL_APP_NOT_ENABLED\)
  - cephfs_test_runner:
      modules:
        - tasks.mgr.test_progress
