meta:
- desc: |
   install ceph/nautilus latest
tasks:
- install:
    branch: nautilus #tag: v13.2.8
    exclude_packages:
      - librados3
      - ceph-mgr-dashboard
      - ceph-mgr-diskprediction-local
      - ceph-mgr-rook
      - ceph-mgr-cephadm
      - cephadm
      - ceph-immutable-object-cache
    extra_packages:
      - librados2
      - python3-rados
      - python3-rgw
      - python3-rbd
      - python3-cephfs
- print: "**** done installing nautilus"
- ceph:
    log-ignorelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
        ms bind msgr2: false
- exec:
    osd.0:
      - ceph osd require-osd-release nautilus
      - ceph osd set-require-min-compat-client nautilus
- print: "**** done ceph"
