overrides:
  ceph:
    log-ignorelist:
      - missing required features
tasks:
- exec:
    mon.a:
      - ceph fs dump --format=json-pretty
      - ceph fs volume ls
      - ceph fs subvolume ls cephfs
- workunit:
   clients:
     client.0:
     - fs/upgrade/volume_client
   env:
     ACTION: verify
   cleanup: true
- workunit:
   clients:
     client.1:
     - fs/upgrade/volume_client
   env:
     ACTION: verify
   cleanup: true
- print: "**** fs/volume_client verify"
