overrides:
  ceph:
    conf:
      osd:
        osd max markdown count: 1000
    log-ignorelist:
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
      - \(POOL_
      - \(CACHE_POOL_
      - \(SMALLER_PGP_NUM\)
      - \(OBJECT_
      - \(SLOW_OPS\)
      - \(REQUEST_SLOW\)
      - \(TOO_FEW_PGS\)
      - slow request
      - \(MON_DOWN\)
      - osds down
      - mons down
      - flag\(s\) set
      - out of quorum
      - PG_
      - Reduced data availability
      - stuck undersized
      - backfill_toofull
      - is down
      - stuck peering
      - acting
